---
version: 2
updates:
  # update the git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: /
    schedule:
      interval: "daily"
