# file: mysql/tasks/install.yml

- name: MySQL | Load the os specific variables
  include_vars: "{{ansible_os_family | lower}}.yml"

- name: MySQL | Make sure the MySql packages are installed
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items: mysql_packages

- name: MySQL | Ensure MySQL is running
  service:
    name: mysql
    state: started
