# file: xxx/meta/main.yml

galaxy_info:
  author: pjan vandaele
  company: ANXS
  description: install and configure ntp
  min_ansible_version: 1.3
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system

dependencies: []
