---
- include_vars: encrypted.yml

- name: Ensure that directories exist
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www/log"
    - "/srv/www/releases"
    - "/srv/www/shared/config"
    - "/srv/www/shared/images/mps"
    - "/srv/www/shared/images/mpsL"

# TODO Extract php-mysql-apache role
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-curl
    - php5-mysql
    - apache2
    - libapache2-mod-php5
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev
    - ghostscript
    - libxslt1-dev
    - libxml-twig-perl
    - msmtp

- name: Install required gems
  gem: name={{ item.name }} version={{ item.version }} user_install=no state=present
  with_items:
    - {name: nokogiri,      version: 1.4.4}
    - {name: mechanize,     version: 0.9.2}
    - {name: activesupport, version: 3.0.4}
    - {name: builder,       version: 2.1.2}
    - {name: rmagick,       version: 2.13.1}
    - {name: htmlentities,  version: 4.2.1}
    - {name: log4r,         version: 1.1.8}
    - {name: json,          version: 1.8.0}
    - {name: hpricot,       version: 0.6.164}
    - {name: rspec,         version: 2.5.0}
    - {name: rcov,          version: 0.9.9}
    - {name: i18n,          version: 0.5.0}

- name: Enable apache modules
  apache2_module: state=present name={{ item }}
  notify: reload apache
  with_items:
    - expires
    - rewrite

- name: Copy across the php config
  template: src=php.ini dest=/etc/php5/{{ item }}/
  notify: reload apache
  with_items:
    - apache2
    - cli

- name: Copy across the apache config
  template: src=openaustralia.org.au.dev.conf dest=/etc/apache2/sites-available/
  notify: reload apache

- name: Copy across the application config
  template: src=general dest=/srv/www/shared/
  notify: reload apache

- name: Copy across the parser config
  template: src=configuration.yml dest=/srv/www/shared/parser_configuration.yml

- name: Enable virtual host
  file: src="../sites-available/openaustralia.org.au.dev.conf" dest="/etc/apache2/sites-enabled/openaustralia.org.au.dev.conf" state=link
  notify: reload apache

- name: Disable default virtual host
  file: dest="/etc/apache2/sites-enabled/000-default.conf" state=absent
  notify: reload apache

- name: Copy msmtp configuration
  template: src=msmtprc dest=/etc/
