# file: ntp/tasks/main.yml

- name: ntp | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - ntp
    - ntpdate

- name: ntp | Configure ntp (/etc/ntp.conf)
  template:
    src: etc_ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
