---

- name: Install RVM
  include_tasks: 'rvm.yml'
  become: yes
  become_user: '{{ rvm1_user }}'

- name: Install Ruby and Gems
  include_tasks: 'rubies.yml'
  become: yes
  become_user: '{{ rvm1_user }}'
